---
title: "Tradeoff Viés e Variância"
author: "Paulo Cirino Ribeiro Neto"
date: "03/04/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, include = TRUE, eval = TRUE, fig.width = 10, warning = FALSE,
                      message = FALSE)
require('ggplot2')
require('dplyr')
```

## Viés e Variância
Em _Machine Learning_ o problema de viés e variância é conceitualmente uma problema de minização de 2 fontes de erro. 

O viés de um modelo está relacionado com a falta de capacidade que ele têm em aprender as relações entre entrada e saída, de forma geral é definido como a diferença entre valor esperado médio do modelo e a saída real. 

A variância por sua vez, está relacionada com o erro devido a variabilidade entre modelos treinados com dados diferentes da mesma função geradora.

A relação entre os dois tipos de erro é quase sempre inversa, onde um modelo que possui robustez suficiente para não variar o resultado dado amostragens diferentes de uma função geradora, quase nunca é capaz de apredender as relações entre entrada e saída.


## Definição Matemática
Definindo que existe uma variável resposta $y$ que é gerada por ${\displaystyle y=f(x)+\epsilon }$. Criamos uma função $\hat{f}(x)$ de forma que $(y - \hat{f}(x))^2$ o mais proximo de 0.

Podemos definir o problema de viés e variância da seguinte forma:
$${\begin{aligned}{\mathrm  {E}}{\Big [}{\big (}y-{\hat  {f}}(x){\big )}^{2}{\Big ]}&={\mathrm  {Vies}}{\big [}{\hat  {f}}(x){\big ]}^{2}+{\mathrm  {Var}}{\big [}{\hat  {f}}(x){\big ]}+\sigma ^{2}\\\end{aligned}}$$

Onde definimos a variância como:
$${
\begin{align}
\mathrm{Var}[X] = \mathrm{E}[X^2] - \mathrm{E}[X]^2
\end{align}
}$$

E por dedução matemática é possível obter :
$$ {\displaystyle {\begin{aligned}\mathrm {Bias} {\big [}{\hat {f}}(x){\big ]}=\mathrm {E} {\big [}{\hat {f}}(x)-f(x){\big ]}\end{aligned}}} $$

## Material Base
O material base desse trabalho é baseado na plataforma [https://paulocirino.shinyapps.io/BiasAndVariance/](https://paulocirino.shinyapps.io/BiasAndVariance/) que possibilita a visualização do problema viés e variância para diversas funções e modelos de forma interativa, o código fonto da plataforma é aberto no (github)[https://github.com/PauloCirino/]. 